// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/badochov/distributed-shortest-path/src/libs/db/model"
)

func newVertex(db *gorm.DB, opts ...gen.DOOption) vertex {
	_vertex := vertex{}

	_vertex.vertexDo.UseDB(db, opts...)
	_vertex.vertexDo.UseModel(&model.Vertex{})

	tableName := _vertex.vertexDo.TableName()
	_vertex.ALL = field.NewAsterisk(tableName)
	_vertex.ID = field.NewInt64(tableName, "id")
	_vertex.Latitude = field.NewFloat64(tableName, "latitude")
	_vertex.Longitude = field.NewFloat64(tableName, "longitude")
	_vertex.Generation = field.NewUint16(tableName, "generation")

	_vertex.fillFieldMap()

	return _vertex
}

type vertex struct {
	vertexDo vertexDo

	ALL        field.Asterisk
	ID         field.Int64
	Latitude   field.Float64
	Longitude  field.Float64
	Generation field.Uint16

	fieldMap map[string]field.Expr
}

func (v vertex) Table(newTableName string) *vertex {
	v.vertexDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v vertex) As(alias string) *vertex {
	v.vertexDo.DO = *(v.vertexDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *vertex) updateTableName(table string) *vertex {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewInt64(table, "id")
	v.Latitude = field.NewFloat64(table, "latitude")
	v.Longitude = field.NewFloat64(table, "longitude")
	v.Generation = field.NewUint16(table, "generation")

	v.fillFieldMap()

	return v
}

func (v *vertex) WithContext(ctx context.Context) *vertexDo { return v.vertexDo.WithContext(ctx) }

func (v vertex) TableName() string { return v.vertexDo.TableName() }

func (v vertex) Alias() string { return v.vertexDo.Alias() }

func (v *vertex) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *vertex) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 4)
	v.fieldMap["id"] = v.ID
	v.fieldMap["latitude"] = v.Latitude
	v.fieldMap["longitude"] = v.Longitude
	v.fieldMap["generation"] = v.Generation
}

func (v vertex) clone(db *gorm.DB) vertex {
	v.vertexDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v vertex) replaceDB(db *gorm.DB) vertex {
	v.vertexDo.ReplaceDB(db)
	return v
}

type vertexDo struct{ gen.DO }

func (v vertexDo) Debug() *vertexDo {
	return v.withDO(v.DO.Debug())
}

func (v vertexDo) WithContext(ctx context.Context) *vertexDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v vertexDo) ReadDB() *vertexDo {
	return v.Clauses(dbresolver.Read)
}

func (v vertexDo) WriteDB() *vertexDo {
	return v.Clauses(dbresolver.Write)
}

func (v vertexDo) Session(config *gorm.Session) *vertexDo {
	return v.withDO(v.DO.Session(config))
}

func (v vertexDo) Clauses(conds ...clause.Expression) *vertexDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v vertexDo) Returning(value interface{}, columns ...string) *vertexDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v vertexDo) Not(conds ...gen.Condition) *vertexDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v vertexDo) Or(conds ...gen.Condition) *vertexDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v vertexDo) Select(conds ...field.Expr) *vertexDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v vertexDo) Where(conds ...gen.Condition) *vertexDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v vertexDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *vertexDo {
	return v.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (v vertexDo) Order(conds ...field.Expr) *vertexDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v vertexDo) Distinct(cols ...field.Expr) *vertexDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v vertexDo) Omit(cols ...field.Expr) *vertexDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v vertexDo) Join(table schema.Tabler, on ...field.Expr) *vertexDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v vertexDo) LeftJoin(table schema.Tabler, on ...field.Expr) *vertexDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v vertexDo) RightJoin(table schema.Tabler, on ...field.Expr) *vertexDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v vertexDo) Group(cols ...field.Expr) *vertexDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v vertexDo) Having(conds ...gen.Condition) *vertexDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v vertexDo) Limit(limit int) *vertexDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v vertexDo) Offset(offset int) *vertexDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v vertexDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *vertexDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v vertexDo) Unscoped() *vertexDo {
	return v.withDO(v.DO.Unscoped())
}

func (v vertexDo) Create(values ...*model.Vertex) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v vertexDo) CreateInBatches(values []*model.Vertex, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v vertexDo) Save(values ...*model.Vertex) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v vertexDo) First() (*model.Vertex, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Vertex), nil
	}
}

func (v vertexDo) Take() (*model.Vertex, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Vertex), nil
	}
}

func (v vertexDo) Last() (*model.Vertex, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Vertex), nil
	}
}

func (v vertexDo) Find() ([]*model.Vertex, error) {
	result, err := v.DO.Find()
	return result.([]*model.Vertex), err
}

func (v vertexDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Vertex, err error) {
	buf := make([]*model.Vertex, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v vertexDo) FindInBatches(result *[]*model.Vertex, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v vertexDo) Attrs(attrs ...field.AssignExpr) *vertexDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v vertexDo) Assign(attrs ...field.AssignExpr) *vertexDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v vertexDo) Joins(fields ...field.RelationField) *vertexDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v vertexDo) Preload(fields ...field.RelationField) *vertexDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v vertexDo) FirstOrInit() (*model.Vertex, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Vertex), nil
	}
}

func (v vertexDo) FirstOrCreate() (*model.Vertex, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Vertex), nil
	}
}

func (v vertexDo) FindByPage(offset int, limit int) (result []*model.Vertex, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v vertexDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v vertexDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v vertexDo) Delete(models ...*model.Vertex) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *vertexDo) withDO(do gen.Dao) *vertexDo {
	v.DO = *do.(*gen.DO)
	return v
}
