apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-cleaner
  namespace: shortest-path
spec:
  template:
    spec:
      containers:
        - name: postgres-cleaner
          image: shortest-path/postgres_cleaner:0.0.1
          envFrom:
            - configMapRef:
                name: postgres-config
      restartPolicy: Never
  backoffLimit: 4