---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: endpoint-observer
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: endpoint-observer
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
    resources:
      - endpoints
    verbs:
      - get
      - list
      - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: endpoint-observer
  namespace: shortest-path
subjects:
  - kind: ServiceAccount
    name: endpoint-observer
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: endpoint-observer