---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker
  namespace: shortest-path
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: endpoint-observer
  namespace: shortest-path
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - watch
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-observer
  namespace: shortest-path
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: endpoint-observer
  namespace: shortest-path
subjects:
  - kind: ServiceAccount
    name: worker
    namespace: shortest-path
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: endpoint-observer
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-observer
  namespace: shortest-path
subjects:
  - kind: ServiceAccount
    name: worker
    namespace: shortest-path
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pods-observer