apiVersion: v1
kind: ConfigMap
metadata:
  namespace: shortest-path
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: psltest
  POSTGRES_HOST: "postgres.postgres.svc.cluster.local"
  POSTGRES_PORT: "5432"