apiVersion: v1
kind: ConfigMap
metadata:
  namespace: shortest-path
  name: shortest-path-commons-config
  labels:
    app: shortest-path
data:
  NAMESPACE: shortest-path
  WORKER_SERVER_PORT: "8080"
