---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workers-manager
  namespace: shortest-path
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-scaler
  namespace: shortest-path
rules:
  - apiGroups:
      - apps
    resources:
      - deployments/scale
    verbs: ["get", "update", "patch"]
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: workers-manager
  namespace: shortest-path
subjects:
  - kind: ServiceAccount
    name: workers-manager
    namespace: shortest-path
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-scaler