apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: workers-region-{{.Region}}
  labels:
    app: workers
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: workers-region-{{.Region}}
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70