apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: shortest-path
  labels:
    app: manager
spec:
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      serviceAccountName: workers-manager
      containers:
      - name: manager
        image: shortest-path/manager:0.0.1
        env:
          - name: NUM_REGIONS
            value: "16"
          - name: REGION_URL_TEMPLATE
            value: workers-region-%d.shortest-path.svc.cluster.local
          - name: REGION_DEPLOYMENT_TEMPLATE
            value: workers-region-%d
          - name: PORT
            value: "8080"
        envFrom:
          - configMapRef:
              name: postgres-config
          - configMapRef:
              name: shortest-path-commons-config
        ports:
        - containerPort: 8080
        livenessProbe:
            httpGet:
                path: /healthz
                port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3